/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TnRouteImport } from './routes/tn'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MsRouteImport } from './routes/ms'
import { Route as LaRouteImport } from './routes/la'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ArRouteImport } from './routes/ar'
import { Route as AlRouteImport } from './routes/al'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TnWhyWeBuiltThisRouteImport } from './routes/tn_.why-we-built-this'
import { Route as TnHowItWorksRouteImport } from './routes/tn_.how-it-works'
import { Route as TnAboutRouteImport } from './routes/tn_.about'
import { Route as MsHowItWorksRouteImport } from './routes/ms_.how-it-works'
import { Route as MsAboutRouteImport } from './routes/ms_.about'
import { Route as LaHowItWorksRouteImport } from './routes/la_.how-it-works'
import { Route as LaAboutRouteImport } from './routes/la_.about'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ArHowItWorksRouteImport } from './routes/ar_.how-it-works'
import { Route as ArAboutRouteImport } from './routes/ar_.about'
import { Route as AlHowItWorksRouteImport } from './routes/al_.how-it-works'
import { Route as AlAboutRouteImport } from './routes/al_.about'
import { Route as TnHowItWorksIncomeRouteImport } from './routes/tn_.how-it-works.income'
import { Route as MsHowItWorksIncomeRouteImport } from './routes/ms_.how-it-works.income'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LaHowItWorksIncomeRouteImport } from './routes/la_.how-it-works.income'
import { Route as ArHowItWorksIncomeRouteImport } from './routes/ar_.how-it-works.income'
import { Route as AlHowItWorksIncomeRouteImport } from './routes/al_.how-it-works.income'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TnRoute = TnRouteImport.update({
  id: '/tn',
  path: '/tn',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MsRoute = MsRouteImport.update({
  id: '/ms',
  path: '/ms',
  getParentRoute: () => rootRouteImport,
} as any)
const LaRoute = LaRouteImport.update({
  id: '/la',
  path: '/la',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlRoute = AlRouteImport.update({
  id: '/al',
  path: '/al',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TnWhyWeBuiltThisRoute = TnWhyWeBuiltThisRouteImport.update({
  id: '/tn_/why-we-built-this',
  path: '/tn/why-we-built-this',
  getParentRoute: () => rootRouteImport,
} as any)
const TnHowItWorksRoute = TnHowItWorksRouteImport.update({
  id: '/tn_/how-it-works',
  path: '/tn/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const TnAboutRoute = TnAboutRouteImport.update({
  id: '/tn_/about',
  path: '/tn/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MsHowItWorksRoute = MsHowItWorksRouteImport.update({
  id: '/ms_/how-it-works',
  path: '/ms/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MsAboutRoute = MsAboutRouteImport.update({
  id: '/ms_/about',
  path: '/ms/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LaHowItWorksRoute = LaHowItWorksRouteImport.update({
  id: '/la_/how-it-works',
  path: '/la/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LaAboutRoute = LaAboutRouteImport.update({
  id: '/la_/about',
  path: '/la/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArHowItWorksRoute = ArHowItWorksRouteImport.update({
  id: '/ar_/how-it-works',
  path: '/ar/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/ar_/about',
  path: '/ar/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlHowItWorksRoute = AlHowItWorksRouteImport.update({
  id: '/al_/how-it-works',
  path: '/al/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AlAboutRoute = AlAboutRouteImport.update({
  id: '/al_/about',
  path: '/al/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TnHowItWorksIncomeRoute = TnHowItWorksIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => TnHowItWorksRoute,
} as any)
const MsHowItWorksIncomeRoute = MsHowItWorksIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => MsHowItWorksRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LaHowItWorksIncomeRoute = LaHowItWorksIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => LaHowItWorksRoute,
} as any)
const ArHowItWorksIncomeRoute = ArHowItWorksIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => ArHowItWorksRoute,
} as any)
const AlHowItWorksIncomeRoute = AlHowItWorksIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AlHowItWorksRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/al': typeof AlRoute
  '/ar': typeof ArRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/la': typeof LaRoute
  '/ms': typeof MsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tn': typeof TnRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/al/about': typeof AlAboutRoute
  '/al/how-it-works': typeof AlHowItWorksRouteWithChildren
  '/ar/about': typeof ArAboutRoute
  '/ar/how-it-works': typeof ArHowItWorksRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/la/about': typeof LaAboutRoute
  '/la/how-it-works': typeof LaHowItWorksRouteWithChildren
  '/ms/about': typeof MsAboutRoute
  '/ms/how-it-works': typeof MsHowItWorksRouteWithChildren
  '/tn/about': typeof TnAboutRoute
  '/tn/how-it-works': typeof TnHowItWorksRouteWithChildren
  '/tn/why-we-built-this': typeof TnWhyWeBuiltThisRoute
  '/al/how-it-works/income': typeof AlHowItWorksIncomeRoute
  '/ar/how-it-works/income': typeof ArHowItWorksIncomeRoute
  '/la/how-it-works/income': typeof LaHowItWorksIncomeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ms/how-it-works/income': typeof MsHowItWorksIncomeRoute
  '/tn/how-it-works/income': typeof TnHowItWorksIncomeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/al': typeof AlRoute
  '/ar': typeof ArRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/la': typeof LaRoute
  '/ms': typeof MsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tn': typeof TnRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/al/about': typeof AlAboutRoute
  '/al/how-it-works': typeof AlHowItWorksRouteWithChildren
  '/ar/about': typeof ArAboutRoute
  '/ar/how-it-works': typeof ArHowItWorksRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/la/about': typeof LaAboutRoute
  '/la/how-it-works': typeof LaHowItWorksRouteWithChildren
  '/ms/about': typeof MsAboutRoute
  '/ms/how-it-works': typeof MsHowItWorksRouteWithChildren
  '/tn/about': typeof TnAboutRoute
  '/tn/how-it-works': typeof TnHowItWorksRouteWithChildren
  '/tn/why-we-built-this': typeof TnWhyWeBuiltThisRoute
  '/al/how-it-works/income': typeof AlHowItWorksIncomeRoute
  '/ar/how-it-works/income': typeof ArHowItWorksIncomeRoute
  '/la/how-it-works/income': typeof LaHowItWorksIncomeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ms/how-it-works/income': typeof MsHowItWorksIncomeRoute
  '/tn/how-it-works/income': typeof TnHowItWorksIncomeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/al': typeof AlRoute
  '/ar': typeof ArRoute
  '/calculator': typeof CalculatorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/la': typeof LaRoute
  '/ms': typeof MsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tn': typeof TnRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/al_/about': typeof AlAboutRoute
  '/al_/how-it-works': typeof AlHowItWorksRouteWithChildren
  '/ar_/about': typeof ArAboutRoute
  '/ar_/how-it-works': typeof ArHowItWorksRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/la_/about': typeof LaAboutRoute
  '/la_/how-it-works': typeof LaHowItWorksRouteWithChildren
  '/ms_/about': typeof MsAboutRoute
  '/ms_/how-it-works': typeof MsHowItWorksRouteWithChildren
  '/tn_/about': typeof TnAboutRoute
  '/tn_/how-it-works': typeof TnHowItWorksRouteWithChildren
  '/tn_/why-we-built-this': typeof TnWhyWeBuiltThisRoute
  '/al_/how-it-works/income': typeof AlHowItWorksIncomeRoute
  '/ar_/how-it-works/income': typeof ArHowItWorksIncomeRoute
  '/la_/how-it-works/income': typeof LaHowItWorksIncomeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/ms_/how-it-works/income': typeof MsHowItWorksIncomeRoute
  '/tn_/how-it-works/income': typeof TnHowItWorksIncomeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/al'
    | '/ar'
    | '/calculator'
    | '/how-it-works'
    | '/la'
    | '/ms'
    | '/sitemap.xml'
    | '/tn'
    | '/unsubscribe'
    | '/al/about'
    | '/al/how-it-works'
    | '/ar/about'
    | '/ar/how-it-works'
    | '/email/unsubscribe'
    | '/la/about'
    | '/la/how-it-works'
    | '/ms/about'
    | '/ms/how-it-works'
    | '/tn/about'
    | '/tn/how-it-works'
    | '/tn/why-we-built-this'
    | '/al/how-it-works/income'
    | '/ar/how-it-works/income'
    | '/la/how-it-works/income'
    | '/lovable/email/suppression'
    | '/ms/how-it-works/income'
    | '/tn/how-it-works/income'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/al'
    | '/ar'
    | '/calculator'
    | '/how-it-works'
    | '/la'
    | '/ms'
    | '/sitemap.xml'
    | '/tn'
    | '/unsubscribe'
    | '/al/about'
    | '/al/how-it-works'
    | '/ar/about'
    | '/ar/how-it-works'
    | '/email/unsubscribe'
    | '/la/about'
    | '/la/how-it-works'
    | '/ms/about'
    | '/ms/how-it-works'
    | '/tn/about'
    | '/tn/how-it-works'
    | '/tn/why-we-built-this'
    | '/al/how-it-works/income'
    | '/ar/how-it-works/income'
    | '/la/how-it-works/income'
    | '/lovable/email/suppression'
    | '/ms/how-it-works/income'
    | '/tn/how-it-works/income'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/al'
    | '/ar'
    | '/calculator'
    | '/how-it-works'
    | '/la'
    | '/ms'
    | '/sitemap.xml'
    | '/tn'
    | '/unsubscribe'
    | '/al_/about'
    | '/al_/how-it-works'
    | '/ar_/about'
    | '/ar_/how-it-works'
    | '/email/unsubscribe'
    | '/la_/about'
    | '/la_/how-it-works'
    | '/ms_/about'
    | '/ms_/how-it-works'
    | '/tn_/about'
    | '/tn_/how-it-works'
    | '/tn_/why-we-built-this'
    | '/al_/how-it-works/income'
    | '/ar_/how-it-works/income'
    | '/la_/how-it-works/income'
    | '/lovable/email/suppression'
    | '/ms_/how-it-works/income'
    | '/tn_/how-it-works/income'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlRoute: typeof AlRoute
  ArRoute: typeof ArRoute
  CalculatorRoute: typeof CalculatorRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LaRoute: typeof LaRoute
  MsRoute: typeof MsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TnRoute: typeof TnRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AlAboutRoute: typeof AlAboutRoute
  AlHowItWorksRoute: typeof AlHowItWorksRouteWithChildren
  ArAboutRoute: typeof ArAboutRoute
  ArHowItWorksRoute: typeof ArHowItWorksRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LaAboutRoute: typeof LaAboutRoute
  LaHowItWorksRoute: typeof LaHowItWorksRouteWithChildren
  MsAboutRoute: typeof MsAboutRoute
  MsHowItWorksRoute: typeof MsHowItWorksRouteWithChildren
  TnAboutRoute: typeof TnAboutRoute
  TnHowItWorksRoute: typeof TnHowItWorksRouteWithChildren
  TnWhyWeBuiltThisRoute: typeof TnWhyWeBuiltThisRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tn': {
      id: '/tn'
      path: '/tn'
      fullPath: '/tn'
      preLoaderRoute: typeof TnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ms': {
      id: '/ms'
      path: '/ms'
      fullPath: '/ms'
      preLoaderRoute: typeof MsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la': {
      id: '/la'
      path: '/la'
      fullPath: '/la'
      preLoaderRoute: typeof LaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al': {
      id: '/al'
      path: '/al'
      fullPath: '/al'
      preLoaderRoute: typeof AlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tn_/why-we-built-this': {
      id: '/tn_/why-we-built-this'
      path: '/tn/why-we-built-this'
      fullPath: '/tn/why-we-built-this'
      preLoaderRoute: typeof TnWhyWeBuiltThisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tn_/how-it-works': {
      id: '/tn_/how-it-works'
      path: '/tn/how-it-works'
      fullPath: '/tn/how-it-works'
      preLoaderRoute: typeof TnHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tn_/about': {
      id: '/tn_/about'
      path: '/tn/about'
      fullPath: '/tn/about'
      preLoaderRoute: typeof TnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ms_/how-it-works': {
      id: '/ms_/how-it-works'
      path: '/ms/how-it-works'
      fullPath: '/ms/how-it-works'
      preLoaderRoute: typeof MsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ms_/about': {
      id: '/ms_/about'
      path: '/ms/about'
      fullPath: '/ms/about'
      preLoaderRoute: typeof MsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la_/how-it-works': {
      id: '/la_/how-it-works'
      path: '/la/how-it-works'
      fullPath: '/la/how-it-works'
      preLoaderRoute: typeof LaHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la_/about': {
      id: '/la_/about'
      path: '/la/about'
      fullPath: '/la/about'
      preLoaderRoute: typeof LaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/how-it-works': {
      id: '/ar_/how-it-works'
      path: '/ar/how-it-works'
      fullPath: '/ar/how-it-works'
      preLoaderRoute: typeof ArHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/about': {
      id: '/ar_/about'
      path: '/ar/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al_/how-it-works': {
      id: '/al_/how-it-works'
      path: '/al/how-it-works'
      fullPath: '/al/how-it-works'
      preLoaderRoute: typeof AlHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/al_/about': {
      id: '/al_/about'
      path: '/al/about'
      fullPath: '/al/about'
      preLoaderRoute: typeof AlAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tn_/how-it-works/income': {
      id: '/tn_/how-it-works/income'
      path: '/income'
      fullPath: '/tn/how-it-works/income'
      preLoaderRoute: typeof TnHowItWorksIncomeRouteImport
      parentRoute: typeof TnHowItWorksRoute
    }
    '/ms_/how-it-works/income': {
      id: '/ms_/how-it-works/income'
      path: '/income'
      fullPath: '/ms/how-it-works/income'
      preLoaderRoute: typeof MsHowItWorksIncomeRouteImport
      parentRoute: typeof MsHowItWorksRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la_/how-it-works/income': {
      id: '/la_/how-it-works/income'
      path: '/income'
      fullPath: '/la/how-it-works/income'
      preLoaderRoute: typeof LaHowItWorksIncomeRouteImport
      parentRoute: typeof LaHowItWorksRoute
    }
    '/ar_/how-it-works/income': {
      id: '/ar_/how-it-works/income'
      path: '/income'
      fullPath: '/ar/how-it-works/income'
      preLoaderRoute: typeof ArHowItWorksIncomeRouteImport
      parentRoute: typeof ArHowItWorksRoute
    }
    '/al_/how-it-works/income': {
      id: '/al_/how-it-works/income'
      path: '/income'
      fullPath: '/al/how-it-works/income'
      preLoaderRoute: typeof AlHowItWorksIncomeRouteImport
      parentRoute: typeof AlHowItWorksRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlHowItWorksRouteChildren {
  AlHowItWorksIncomeRoute: typeof AlHowItWorksIncomeRoute
}

const AlHowItWorksRouteChildren: AlHowItWorksRouteChildren = {
  AlHowItWorksIncomeRoute: AlHowItWorksIncomeRoute,
}

const AlHowItWorksRouteWithChildren = AlHowItWorksRoute._addFileChildren(
  AlHowItWorksRouteChildren,
)

interface ArHowItWorksRouteChildren {
  ArHowItWorksIncomeRoute: typeof ArHowItWorksIncomeRoute
}

const ArHowItWorksRouteChildren: ArHowItWorksRouteChildren = {
  ArHowItWorksIncomeRoute: ArHowItWorksIncomeRoute,
}

const ArHowItWorksRouteWithChildren = ArHowItWorksRoute._addFileChildren(
  ArHowItWorksRouteChildren,
)

interface LaHowItWorksRouteChildren {
  LaHowItWorksIncomeRoute: typeof LaHowItWorksIncomeRoute
}

const LaHowItWorksRouteChildren: LaHowItWorksRouteChildren = {
  LaHowItWorksIncomeRoute: LaHowItWorksIncomeRoute,
}

const LaHowItWorksRouteWithChildren = LaHowItWorksRoute._addFileChildren(
  LaHowItWorksRouteChildren,
)

interface MsHowItWorksRouteChildren {
  MsHowItWorksIncomeRoute: typeof MsHowItWorksIncomeRoute
}

const MsHowItWorksRouteChildren: MsHowItWorksRouteChildren = {
  MsHowItWorksIncomeRoute: MsHowItWorksIncomeRoute,
}

const MsHowItWorksRouteWithChildren = MsHowItWorksRoute._addFileChildren(
  MsHowItWorksRouteChildren,
)

interface TnHowItWorksRouteChildren {
  TnHowItWorksIncomeRoute: typeof TnHowItWorksIncomeRoute
}

const TnHowItWorksRouteChildren: TnHowItWorksRouteChildren = {
  TnHowItWorksIncomeRoute: TnHowItWorksIncomeRoute,
}

const TnHowItWorksRouteWithChildren = TnHowItWorksRoute._addFileChildren(
  TnHowItWorksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlRoute: AlRoute,
  ArRoute: ArRoute,
  CalculatorRoute: CalculatorRoute,
  HowItWorksRoute: HowItWorksRoute,
  LaRoute: LaRoute,
  MsRoute: MsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TnRoute: TnRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AlAboutRoute: AlAboutRoute,
  AlHowItWorksRoute: AlHowItWorksRouteWithChildren,
  ArAboutRoute: ArAboutRoute,
  ArHowItWorksRoute: ArHowItWorksRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LaAboutRoute: LaAboutRoute,
  LaHowItWorksRoute: LaHowItWorksRouteWithChildren,
  MsAboutRoute: MsAboutRoute,
  MsHowItWorksRoute: MsHowItWorksRouteWithChildren,
  TnAboutRoute: TnAboutRoute,
  TnHowItWorksRoute: TnHowItWorksRouteWithChildren,
  TnWhyWeBuiltThisRoute: TnWhyWeBuiltThisRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
